### ISSUE TITLE
accessibility: font colours

### ISSUE THREAD

**Issue by fionafreemark** [shopper-mapper-org/median#18]
The font/icon colours in the nav don't have quite enough contrast to meet accessibility standards. 
The blue on grey has a [contrast-ratio of 3.57](https://contrast-ratio.com/#%235BC5FF-on-%235A5A5A).
Also the [white on grey is rated 2.51](https://contrast-ratio.com/#%23ffffff-on-%239FA3B1). 
I think these might be fixed by making the grey tones a bit darker for more contrast! :)

**Comment by graydonj** [comment]
Font colors accessible!
