### ISSUE TITLE
Issue: results show locations not local to current location

### ISSUE THREAD

**Issue by caryltan** [shopper-mapper-org/median#19]
- used "use my location" (L5J 1S1) and results brought back two addresses in the UK 

![Screenshot 2023-02-21 at 12 23 45 PM](https://user-images.githubusercontent.com/40412421/220416469-a97abb95-21c4-4770-a642-eaab57e3d830.png)

**Comment by caryltan** [comment]
We looked more into it and it looks like only an issue when you use postal code for your location or "use my location", which essentially is drawing from postal code anyway? 

not an issue at all when using cities since it auto-completes with country to keep it local (i.e. Toronto, CA)

**Comment by johnmal-dev** [comment]
conditional rendering of 'Results' and 'Faves' header

**Comment by graydonj** [comment]
Now using ternary for conditional render of "Results" or "Favourites" depending on view.
