### ISSUE TITLE
Default map view size

### ISSUE THREAD

**Issue by nobrayn** [shopper-mapper-org/median#23]
It would be pretty keen to have the map view zoomed in to something closer to what the user selected for range. Searching at 20km and then searching at 1km doesn't change the view currently, so if a user is searching for something in a walkable distance from home, they have to zoom in to see what's around.

I noticed it also zooms back out when you favourite an item.

![Screen Shot 2023-02-21 at 12 40 00](https://user-images.githubusercontent.com/92102282/220419746-689d04ab-9e35-44a9-b1cd-d765a37a37d2.png)

**Comment by johnmal-dev** [comment]
zoom level now updates based on range:
- 1-4 km: 13 zoom
- 5-14 km: 12 zoom
- 15-20 km: 11 zoom
