### ISSUE TITLE
contact page: media queries

### ISSUE THREAD

**Issue by fionafreemark** [shopper-mapper-org/median#30]
small tweak: on mobile view your profile boxes all squish together and it would be nice if they stacked in a column so we could see them all on a larger scale!
<img width="446" alt="Screen Shot 2023-02-21 at 12 44 50 PM" src="https://user-images.githubusercontent.com/79855684/220420561-c5e55fbf-50b2-4f1a-af45-486b247a1793.png">

**Comment by graydonj** [comment]
Team member boxes now flex into a column at an appropriate breakpoint
