### ISSUE TITLE
Suggestion: hover for legend info

### ISSUE THREAD

**Issue by caryltan** [shopper-mapper-org/median#34]
iconography is a bit confusing at a glance on the difference between icons. Maybe a hover or blurb or page that goes over what median result vs regular result means?

![Screenshot 2023-02-21 at 12 52 07 PM](https://user-images.githubusercontent.com/40412421/220422173-a3c8bca5-eb50-48b9-bf3b-4b544a09b877.png)

**Comment by graydonj** [comment]
Added Legend Icon descriptions to About page
