### ISSUE TITLE
Issue: Icon Inconsistency and styling issue

### ISSUE THREAD

**Issue by caryltan** [shopper-mapper-org/median#36]
Icons right now are unclear why legend icons are round vs pin shaped. i.e. median vs median selected are two different styles yet result and selected are both pins, and fave and selected fave are both round?

getting a "squished" look when moving from median result to median selected and "M" gets squished" when selecting from results list

![Screenshot 2023-02-21 at 12 55 59 PM](https://user-images.githubusercontent.com/40412421/220422987-cfd8c063-3fd8-461f-bb35-f62e0b9e1618.png)
![Screenshot 2023-02-21 at 12 55 55 PM](https://user-images.githubusercontent.com/40412421/220422990-0bf0883f-1d4a-47ed-9e35-dd2200296d99.png)

**Comment by graydonj** [comment]
Updated Median Highlighted icon to be the same style as Median.
