### ISSUE TITLE
Issue: Footer with grey bar

### ISSUE THREAD

**Issue by caryltan** [shopper-mapper-org/median#37]
getting a grey bar below the footer on some browsers:
- Chrome is good!
- Firefox Desktop (apprx 1900px) and some smaller sizes
- Safari Desktop

![Screenshot 2023-02-21 at 1 02 21 PM](https://user-images.githubusercontent.com/40412421/220424357-2f4e32dc-7150-436c-bc69-9dc1dbb758b8.png)

**Comment by johnmal-dev** [comment]
fixed spacing issues using flexbox
