### ISSUE TITLE
Results list on mobile showing 0 items

### ISSUE THREAD

**Issue by johnmal-dev** [shopper-mapper-org/median#38]

**Comment by johnmal-dev** [comment]
![image](https://user-images.githubusercontent.com/56036354/220446285-cc7f965d-d9a3-4760-9ee0-45e6e4fc41af.png)

**Comment by johnmal-dev** [comment]
## Research
After some google-fu, this appears to be a feature (not a bug) for mobile browsers. 

The OS/Browser determines the behaviour of `<select>` elements. In the case of our mobile browsers, we are given a single clickable input (ie '0 items') that opens the complete list of options.

Here's a stack-overflow answer on this topic: https://stackoverflow.com/questions/56344229/display-a-traditional-html-select-list-on-ios

## Proposed Solution
If we cannot show the results list without clicking, change the Results list to a single clickable results input button.

**Comment by johnmal-dev** [comment]
## Dropdown example

<img width="347" alt="Screenshot 2023-02-21 at 9 25 41 PM" src="https://user-images.githubusercontent.com/56036354/220505043-63243a81-d1da-418e-919e-3b8c9f5bb0fc.png">

**Comment by graydonj** [comment]
Current implementation involves making the select box into a dropdown for mobile-size screens, but we don't love that fix.

**Comment by johnmal-dev** [comment]
resolved with commit f9bc8283071be46722547a8cdb50f1a9cea8a3ca
